version: "3"
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '6379:6379'
  
  mongo:
    image: mongo
    ports:
      - 2717:27017
    restart: unless-stopped
    network_mode: bridge
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
      MONGO_INITDB_DATABASE: football-fixures
    volumes:
      - mongo:/data/db
  
  api:
    build: 
      context: .
      target: development
    container_name: api   
    network_mode: bridge
    restart: unless-stopped
    command: npm run start
    ports:
      - 8080:5007
    volumes:
      - .:/src
      - /src/node_modules
    environment:
       NODE_ENV: 5007
       REDIS_URL: redis://cache
       ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: example
       JWT_SECRET: mysecret
       REDIS_PORT: 6379
    links:
      - mongo

  
  
volumes:
  mongo: {}