name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  image-build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test run docker build
        run: docker build -t lendapi .

  deploy:
    needs: image-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lendapi"
          heroku_email: ${{secrets.DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production